content/getting-started/zymkey4i.md, themes/docsy/assets/scss/_variables.scss
This is just a placeholder until we move real content over along with the API docs.
=> Changed wording on Getting Started to reference back to Community for now.

content/getting-started/zymkey4/quickstart/index.md, content/reference/cpu-scaling.md, content/troubleshooting/general/index.md
- Added disable unattended-upgrade warning to known issues
- Cleaned up links to known issues, cpu governor, etc.
=> Added known issue and cleaned up links

content/tutorials/digital-wallet/index.md
Fixed the links in wallet tutorial. Changed all hsm6 to HSM6. Replaced html with markdown.
=> Fixed links in wallet tutorial

content/api/_index.md, content/getting-started/_index.md, content/getting-started/hsm4/_index.md, content/getting-started/hsm4/quickstart/index.md, content/getting-started/hsm6/_index.md, content/getting-started/hsm6/quickstart/index.md, content/getting-started/zymkey4/_index.md, content/getting-started/zymkey4/production-mode/index.md, content/getting-started/zymkey4/quickstart/index.md, content/reference/_index.md, content/reference/binding/index.md, content/reference/cad/_index.md, content/reference/cad/hsm4/index.md, content/reference/cad/hsm6/index.md, content/reference/cad/zymkey4/index.md, content/reference/conformity/_index.md, content/reference/conformity/hsm4/index.md, content/reference/conformity/hsm6/index.md, content/reference/conformity/zymkey4/index.md, content/reference/power-quality/index.md, content/reference/product-briefs/_index.md, content/reference/real-time-clock/index.md
Added aliases to front matter for old locations to redirect to new locations. Fixed api, getting-started, and reference.
=> Aliases for old file locations

content/getting-started/hsm4/quickstart/index.md, content/getting-started/hsm6/quickstart/index.md, content/getting-started/zymkey4/quickstart/index.md
Added to all three quickstarts
=> Added workaround to install bullseye 64 bit

config/_default/menu.yaml, content/tutorials/digital-wallet/oversight-example/index.md
*   Added the oversight wallet tutorial
*   swapped zymbit.com link for github on main menu
=> Bobg off main2

config/_default/menu.yaml
Changed icon on navbar from discourse to home for zymbit.com.
=> Small icon update

config/_default/params.yaml
Turned on local site search using lunr.js.
=> Update params.yaml: add local site search

content/getting-started/scm/production-mode/index.md
merging prod mode page in to catchup work in progress
=> Add: draft SCM Prod Mode

content/troubleshooting/scm/index.md, content/tutorials/encrypt-rfs/index.md
Merging in the warning callout on encryption in main.
Adding release note info to SCM Troubleshooting for second Alpha release,(fw 00.00.31Alpha) units 3 and up.
=> Merge from main and fw .31 update

content/reference/reserved-pins/index.md
Added doc with SCM reserved PINs to reference section
=> Add doc for reserved pins

content/getting-started/scm/index.md
Created an SCM index as a placeholder to help get new users to beta site
=> Merge in SCM (beta) link

content/getting-started/scm/index.md
updating my working branch to any changes from main
=> Removed "beta" from linkTitle

themes/zymdocsy/layouts/partials/head.html
google_news template no longer supported
=> Update head.html: remove google_news template

content/reference/cad/developerkit2/index.md
=> Add IO step file

content/getting-started/hsm4/quickstart/index.md, content/getting-started/hsm6/quickstart/index.md
Populated GPIO notice for 6.6 kernel to HSM4 and HSM6.
=> Finish 6.6x note

content/bootware-one-zero-general/_index.md
Added a message suggesting to use PIs with at least 4MB RAM.
=> Update _index.md - Add RAM reqts

content/device-addons/_index.md, content/device-addons/i225-ethernet-card/index.md, content/device-addons/i255-ethernet-controller.md, themes/zymdocsy/assets/scss/_sidebar-tree.scss
=> side-nav-fix

content/getting-started/scm/quickstart/index.md, content/troubleshooting/scm/index.md
Added Notice blocks for issue #159. Added to SCM quickstart and Troubleshooting SCM. Cleaned up fw versions and supported OS' that weren't updated.
=> Update bug 159 notice

content/device-addons/_index.md, content/device-addons/i225-ethernet-card/index.md
resolving conflicts from pulling some i225 updates
=> add application page for I225 ethernet

content/_index.md, content/bootware/getting-started/_index.md, content/bootware/image-files/index.md
customer complained they can't have a release candidate
=> Uprev'd release from saying -rc.26 to -27

content/bootware/image-files/index.md
Updated example bootware images with latest OS and bootware 1.2.2
=> added links for 1.2.2 bootware images

content/bootware/_index.md, content/bootware/getting-started/_index.md
Minor update to add a reference that a free Zymkey is available when signing up for a free Bootware trial; provide link to signup page.
=> Added ref to getting a free zymkey w/ bootware signup

content/_index.md, content/bootware1.3.1/archive/bootware-one-zero-general/features/development/index.md, content/bootware1.3.1/archive/bootware-one-zero-general/getting-started/_index.md, content/bootware1.3.1/archive/bootware-one-zero/features/development/index.md, content/bootware1.3.1/archive/bootware-one-zero/getting-started/_index.md, content/bootware1.3.1/archive/bootware1.3.0/features/development/index.md, content/bootware1.3.1/archive/bootware1.3.0/getting-started/_index.md, content/bootware1.3.1/features/development/index.md, content/bootware1.3.1/getting-started/_index.md, content/bootware1.3.1/image-files/index.md, content/bootware1.3.1/troubleshooting/_index.md, content/bootware1.3.1/troubleshooting/pizero-bullseye/index.md, content/getting-started/hsm4/production-mode/index.md, content/getting-started/hsm4/quickstart/index.md, content/getting-started/hsm6/production-mode/index.md, content/getting-started/hsm6/quickstart/index.md, content/getting-started/scm/quickstart/index.md, content/getting-started/zymkey4/production-mode/index.md, content/getting-started/zymkey4/quickstart/index.md, content/reference/product-briefs/hsm64.md, content/troubleshooting/general/index.md, content/troubleshooting/scm/index.md, content/tutorials/aws-iot/verify-sigs/index.md, content/tutorials/digital-wallet/oversight-example/index.md, content/tutorials/digital-wallet/slip39-example/index.md, content/tutorials/digital-wallet/wallet-example/index.md
- Added additional steps to update boot artifacts for Pi0 for bullseye
- Added example zi pi0 with bullseye
- Changed references from Zymbit Core Software to Zymbit Driver Package
- Misc cleanup of links
=> 1.3.1 addl info for bullseye on pi0

content/bootware1.3.1/image-files/index.md
Adding example image links for bookworm and jammy on Pi4/CM4.
=> 1.3.2 prelim example image updates
